name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo sysadminctl -addUser mitmproxyuser -admin
          touch mitm_plugin.py
          sudo cp mitm_plugin.py /Users/mitmproxyuser/mitm_plugin.py
